// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PokemonCreateInput struct {
	ID          *string  `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Type        []string `json:"type"`
	Abilities   []string `json:"abilities"`
}

type PokemonUpdateInput struct {
	ID          string    `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Category    *string   `json:"category"`
	Type        []*string `json:"type"`
	Abilities   []*string `json:"abilities"`
}
